//! Man page generation logic.
//!
//! Renders roff man pages for the top-level command and every
//! subcommand, one file per command (pcli2.1, pcli2-folder.1,
//! pcli2-folder-list.1, ...).

use crate::error::CliError;
use std::path::Path;

/// Generate man pages for the full command tree into the given directory.
///
/// Returns the number of pages written.
#[allow(clippy::result_large_err)]
pub fn generate_man_pages(output_dir: &Path) -> Result<usize, CliError> {
    std::fs::create_dir_all(output_dir)
        .map_err(|e| CliError::ActionError(crate::actions::CliActionError::IoError(e)))?;

    let cmd = crate::commands::create_full_command();
    render_command_tree(&cmd, "", output_dir)
}

/// Recursively render a command and its subcommands to `<output_dir>/<name>.1`.
#[allow(clippy::result_large_err)]
fn render_command_tree(
    cmd: &clap::Command,
    name_prefix: &str,
    output_dir: &Path,
) -> Result<usize, CliError> {
    let page_name = if name_prefix.is_empty() {
        cmd.get_name().to_string()
    } else {
        format!("{}-{}", name_prefix, cmd.get_name())
    };

    // clap_mangen renders one command per page; give each page the full
    // dash-joined command path as its title so pages don't collide.
    let man = clap_mangen::Man::new(cmd.clone().name(page_name.clone()));
    let mut buffer: Vec<u8> = Vec::new();
    man.render(&mut buffer)
        .map_err(|e| CliError::ActionError(crate::actions::CliActionError::IoError(e)))?;

    let path = output_dir.join(format!("{}.1", page_name));
    std::fs::write(&path, buffer)
        .map_err(|e| CliError::ActionError(crate::actions::CliActionError::IoError(e)))?;

    let mut count = 1;
    for subcommand in cmd.get_subcommands() {
        // Help is auto-generated by clap and not useful as a man page
        if subcommand.get_name() == "help" {
            continue;
        }
        count += render_command_tree(subcommand, &page_name, output_dir)?;
    }

    Ok(count)
}
